name: publish-image

on:
  push:
    branches:
      - 'master'
  schedule:
      - cron: '0 4 1 * *'
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: loomchild
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: loomchild
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  platforms: linux/amd64,linux/arm64,linux/arm/v7
                  push: true
                  tags: |
                      loomchild/volume-backup:latest
                      ghcr.io/loomchild/volume-backup:latest
